server:
  port: 7000

spring:
  cloud:
    nacos:
      discovery:
        service: skill-service
      server-addr: localhost:8848
  datasource:
    url: jdbc:mysql://localhost:3298/jarvis
    username: ${MYSQL_ACCOUNT}
    password: ${MYSQL_PASSWORD}
  redis:
    host: localhost
    port: 6379
    database: 0