server:
  port: 6000

dubbo:
  application:
    name: user-center
    id: user-center
  registry:
    address: nacos://localhost:8848
  protocol:
    name: dubbo

spring:
  cloud:
    sentinel:
      transport:
        dashboard: localhost:8080
      filter:
        enabled: false

management:
  endpoints:
    web:
      exposure:
        include: '*'