server:
  port: 4001

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      url: jdbc:mysql://localhost:3308/jarvis?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull
      username: ${MYSQL_ACCOUNT}
      password: ${MYSQL_PASSWORD}
      driver-class-name: com.mysql.jdbc.Driver
      # 初始化连接大小，连接池建立时创建的初始化连接数
      initial-size: 5
      # 最小空闲连接数，连接池中最小的活跃连接数
      min-idle: 15
      validation-query: SELECT 1
      # 获取连接时检测，是否在获得连接后检测其可用性
      test-on-borrow: true
      # 是否在连接空闲一段时间后检测其可用性
      test-while-idle: true
      # 连接保持空闲而不被驱逐的最长时间
      time-between-eviction-runs-millis: 60000
      # 有多个datasource时，合并多个datasource监控
      use-global-data-source-stat: true
      # 配置druid显示监控统计
      # http://xx:xxxx/druid
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        reset-enable: false
        login-username: admin
        login-password: admin
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
      max-active: 300
  swagger:
    enabled: true
    title: Jarvis认证中心
    base-package: cn.linjk.jarvis.authmanagement
    contact:
      name: LinJK
    security:
      filter-plugin: true
      username: linjk
      password: 123456

  cloud:
    sentinel:
      transport:
        dashboard: localhost:8080
      filter:
        enabled: true

client:
  oauth2:
    client-id: jarvis-client
    secret: 123321abc.
    grant_types:
      - password
      - refresh_token
    # token 有效时间，单位秒
    token-validity-time: 3600
    refresh-token-validity-time: 3600
    # 客户端访问范围
    scopes:
      - api
      - all
    whites:
      - /actuator/**
      - /public/**
      - /druid/**
      - /static/**
      - /swagger-ui.html
      - /v2/api-docs
      - /v3/swagger-login
      - /swagger-resources
      - /oauth/**

# 指标监控健康检查
management:
  endpoints:
    web:
      exposure:
        include: "*" # 暴露的端点
        exclude: beans,mappings,env

logging:
  config: classpath:logback/logback.xml

mybatis:
  mapper-locations: classpath*:cn/linjk/jarvis/common/mybatis/mapper/xml/*.xml