server:
  port: 4001

spring:
  datasource:
    url: jdbc:log4jdbc:mysql://localhost:3308/jarvis?useUnicode=true&characterEncoding=utf-8
    username: ${MYSQL_ACCOUNT}
    password: ${MYSQL_PASSWORD}
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: net.sf.log4jdbc.DriverSpy
  swagger:
    enabled: true
    title: Jarvis认证中心
    base-package: cn.linjk.jarvis.authmanagement
    contact:
      name: LinJK
    security:
      filter-plugin: true
      username: linjk
      password: 123456

  cloud:
    sentinel:
      transport:
        dashboard: localhost:8080
      filter:
        enabled: true

client:
  oauth2:
    client-id: jarvis-client
    secret: 123321abc.
    grant_types:
      - password
      - refresh_token
    # token 有效时间，单位秒
    token-validity-time: 3600
    refresh-token-validity-time: 3600
    # 客户端访问范围
    scopes:
      - api
      - all

# 指标监控健康检查
management:
  endpoints:
    web:
      exposure:
        include: "*" # 暴露的端点

logging:
  config: classpath:logback/logback.xml