server:
  port: 5001

dubbo:
  application:
    name: ${spring.application.name}
    id: ${spring.application.name}
  registry:
    address: nacos://localhost:8848
  protocol:
    name: dubbo
    port: 50011

spring:
  main:
    allow-bean-definition-overriding: true
  cloud:
    sentinel:
      transport:
        dashboard: localhost:8080
      filter:
        enabled: false

oauth2:
  client:
    client-id: jarvis-client
    secret: 123321abc.
    grant_type: password
    scope: api

service:
  name:
    jarvis-oauth-server: http://auth-service/

management:
  endpoints:
    web:
      exposure:
        include: '*'