# Generated by Django 3.2.5 on 2022-06-08 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sys_code', models.CharField(max_length=32, unique=True, verbose_name='使用系统编码')),
                ('sys_name', models.CharField(max_length=32, verbose_name='使用系统名称')),
                ('create_time', models.DateTimeField(default=True, verbose_name='注册时间')),
            ],
            options={
                'db_table': 'system_info',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ApiInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_method', models.CharField(max_length=32, verbose_name='API请求方式')),
                ('api_uri', models.CharField(max_length=256, verbose_name='API请求URI')),
                ('create_time', models.DateTimeField(default=True, verbose_name='创建时间')),
                ('remark', models.CharField(blank=True, default=None, max_length=256, null=True, verbose_name='备注')),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='test_platform.systeminfo', verbose_name='关联系统')),
            ],
            options={
                'db_table': 'api_info',
                'managed': True,
            },
        ),
    ]
