# Generated by Django 3.2.5 on 2022-06-08 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_platform', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiinfo',
            name='enable',
            field=models.IntegerField(default=1, verbose_name='是否启用'),
        ),
    ]
