server:
  port: 5001

dubbo:
  application:
    name: ${spring.application.name}
    id: ${spring.application.name}
  registry:
    address: nacos://localhost:8848
  protocol:
    name: dubbo
    port: 50011

spring:
  cloud:
    sentinel:
      transport:
        dashboard: localhost:8080
      filter:
        enabled: false
  datasource:
    url: jdbc:mysql://localhost:3308/jarvis
    username: ${MYSQL_ACCOUNT}
    password: ${MYSQL_PASSWORD}
  redis:
    host: localhost
    port: 6379
    database: 0

management:
  endpoints:
    web:
      exposure:
        include: '*'