server:
  port: 5001

dubbo:
  application:
    name: user-service
    id: user-service
  registry:
    address: nacos://localhost:8848
  protocol:
    name: dubbo

spring:
  cloud:
    sentinel:
      transport:
        dashboard: localhost:8080
      filter:
        enabled: false
  datasource:
    url: jdbc:mysql://localhost:3308/jarvis
    username: ${MYSQL_ACCOUNT}
    password: ${MYSQL_PASSWORD}
  redis:
    host: localhost
    port: 6379
    database: 0

management:
  endpoints:
    web:
      exposure:
        include: '*'